# Generated by Django 5.2.1 on 2025-05-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_cart_cartitems_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
