# Generated by Django 5.2.1 on 2025-05-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_cartitems_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255, verbose_name='Correo')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='joyas',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.CreateModel(
            name='ProductosCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_store.compra')),
            ],
        ),
    ]
