# Generated by Django 5.2.1 on 2025-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0005_compra_alter_cartitems_quantity_alter_joyas_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoscompra',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productoscompra',
            name='product_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
