# Generated by Django 5.2.1 on 2025-06-05 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0006_productoscompra_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoscompra',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productoscompra',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_store.joyas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoscompra',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='productoscompra',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
