# Generated by Django 5.2.1 on 2025-06-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0008_compra_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='user',
        ),
    ]
